### ISSUE TITLE
Error: Line 71: Unexpected token ...

### ISSUE THREAD

**Issue by afconlab** [ibi-group/datatools-ui#1012]
error when try to lanch UI
`
> datatools-manager@0.0.0-development start
> mastarm build --env dev --serve --proxy http://localhost:4000/api
(node:7524) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[0003] info  Server running at http://10.20.1.201:9966/ (connect)
`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at isModuleDeclaration (/home/ubuntu/datatools-ui/node_modules/@babel/types/lib/validators/generated/index.js:2748:35)
    at PluginPass.Program (/home/ubuntu/datatools-ui/node_modules/babel-plugin-lodash/lib/index.js:102:44)
Error: Line 71: Unexpected token ...
    at ErrorHandler.constructError (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:5012:22)
    at ErrorHandler.createError (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:5028:27)
    at Parser.unexpectedTokenError (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:1985:39)
    at Parser.throwUnexpectedToken (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:1995:21)
    at Parser.parseObjectPropertyKey (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:2499:33)
    at Parser.parseObjectProperty (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:2534:25)
    at Parser.parseObjectInitializer (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:2602:35)
    at Parser.inheritCoverGrammar (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parsePrimaryExpression (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:2354:38)
    at Parser.inheritCoverGrammar (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parseLeftHandSideExpressionAllowCall (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:2899:26)
    at Parser.inheritCoverGrammar (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parseUpdateExpression (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:3004:26)
    at Parser.parseUnaryExpression (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:3048:26)
    at Parser.inheritCoverGrammar (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parseExponentiationExpression (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:3054:26)
    at Parser.inheritCoverGrammar (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parseBinaryExpression (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:3089:26)
    at Parser.inheritCoverGrammar (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parseConditionalExpression (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:3141:26)
    at Parser.parseAssignmentExpression (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:3250:26)
    at Parser.isolateCoverGrammar (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:2269:37)
    at Parser.parseLexicalBinding (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:3425:34)
    at Parser.parseBindingList (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:3439:27)
    at Parser.parseLexicalDeclaration (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:3461:34)
    at Parser.parseStatementListItem (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:3376:39)
    at Parser.parseFunctionSourceElements (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:4195:29)
    at Parser.parseFunctionDeclaration (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:4347:26)
    at Parser.parseStatementListItem (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:3379:39)
    at Parser.parseScript (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:4723:29)
    at Object.parse (/home/ubuntu/datatools-ui/node_modules/esprima/dist/esprima.js:122:61)
    at transform (/home/ubuntu/datatools-ui/node_modules/envify/custom.js:40:15)
    at Stream.flush (/home/ubuntu/datatools-ui/node_modules/envify/custom.js:81:20)
    at _end (/home/ubuntu/datatools-ui/node_modules/through/index.js:65:9)
    at Stream.stream.end (/home/ubuntu/datatools-ui/node_modules/through/index.js:74:5)
    at DestroyableTransform.onend (/home/ubuntu/datatools-ui/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (node:events:633:28)
    at DestroyableTransform.emit (node:events:531:35)
    at endReadableNT (/home/ubuntu/datatools-ui/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  index: 2472,
  **lineNumber: 71,
  description: 'Unexpected token ...',
  message: 'Line 71: Unexpected token ... while parsing file: /home/ubuntu/datatools-ui/lib/common/util/config.js',
  filename: '/home/ubuntu/datatools-ui/lib/common/util/config.js',
  stream: [Labeled]**
}
TypeError: The "fd" argument must be of type number. Received type string ('dist/index.css')
    at Object.closeSync (node:fs:532:17)
    at Object.closeSync (/home/ubuntu/datatools-ui/node_modules/graceful-fs/graceful-fs.js:74:20)
    at /home/ubuntu/datatools-ui/node_modules/mastarm/lib/css-transform.js:55:14`
## Version of datatools-ui and datatools-server if applicable (exact commit hash or branch name)
 nvm version 0.39.7
 node version V21.7.3 

someone know , how to fix the issue ?
[package.json](https://github.com/ibi-group/datatools-ui/files/15077505/package.json)

**Comment by miles-grant-ibigroup** [comment]
We only support node 14!

**Comment by binh-dam-ibigroup** [comment]
This was fixed by #1045.
