### ISSUE TITLE
Data Tools FeedSource#update storing wrong type (dateCreated as INT64 instead of DATE_TIME)

### ISSUE THREAD

**Issue by landonreed** [ibi-group/datatools-ui#510]
## Observed behavior (please include a screenshot if possible)

MongoDB codec error when fetching a feed source that has just been updated:
```
Oct 28 14:14:21.974 [qtp1259527344-584] ERROR c.c.datatools.manager.DataManager:249 - error
org.bson.codecs.configuration.CodecConfigurationException: Failed to decode 'dateCreated'. readDateTime can only be called when CurrentBSONType is DATE_TIME, not when CurrentBSONType is INT64.
	at org.bson.codecs.pojo.PojoCodecImpl.decodePropertyModel(PojoCodecImpl.java:171)
	at org.bson.codecs.pojo.PojoCodecImpl.decodeProperties(PojoCodecImpl.java:149)
	at org.bson.codecs.pojo.PojoCodecImpl.decode(PojoCodecImpl.java:103)
	at org.bson.codecs.pojo.PojoCodecImpl.decode(PojoCodecImpl.java:107)
	at com.mongodb.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52)
	at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
	at org.bson.codecs.configuration.LazyCodec.decode(LazyCodec.java:47)
	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:101)
	at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
	at com.mongodb.connection.ReplyMessage.<init>(ReplyMessage.java:50)
	at com.mongodb.connection.CommandProtocol.getResponseDocument(CommandProtocol.java:132)
	at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:111)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:159)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:289)
	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:176)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:216)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:207)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:113)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:715)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:709)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:433)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:406)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:709)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:81)
	at com.mongodb.Mongo.execute(Mongo.java:810)
	at com.mongodb.Mongo$2.execute(Mongo.java:797)
	at com.mongodb.OperationIterable.iterator(OperationIterable.java:47)
	at com.mongodb.OperationIterable.forEach(OperationIterable.java:70)
	at com.mongodb.OperationIterable.into(OperationIterable.java:82)
	at com.mongodb.FindIterableImpl.into(FindIterableImpl.java:220)
	at com.conveyal.datatools.manager.persistence.TypedPersistence.getAll(TypedPersistence.java:135)
	at com.conveyal.datatools.manager.controllers.api.FeedSourceController.getAllFeedSources(FeedSourceController.java:60)
	at com.conveyal.datatools.manager.controllers.api.FeedSourceController$$Lambda$105/2083854344.handle(Unknown Source)
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:530)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.bson.BsonInvalidOperationException: readDateTime can only be called when CurrentBSONType is DATE_TIME, not when CurrentBSONType is INT64.
	at org.bson.AbstractBsonReader.verifyBSONType(AbstractBsonReader.java:692)
	at org.bson.AbstractBsonReader.checkPreconditions(AbstractBsonReader.java:724)
	at org.bson.AbstractBsonReader.readDateTime(AbstractBsonReader.java:312)
	at org.bson.codecs.DateCodec.decode(DateCodec.java:37)
	at org.bson.codecs.DateCodec.decode(DateCodec.java:29)
	at org.bson.codecs.DecoderContext.decodeWithChildContext(DecoderContext.java:93)
	at org.bson.codecs.pojo.PojoCodecImpl.decodePropertyModel(PojoCodecImpl.java:165)
	... 56 common frames omitted
```

## Expected behavior

Feed source fetch should occur with no issue after update.

## Steps to reproduce the problem

Create feed source. Update feed source prop (e.g., make deployable). Error will occur when UI dispatches action to fetch feed source.

## Any special notes on configuration used

N/A

## Version of datatools-ui and datatools-server if applicable (exact commit hash or branch name)

The latest PRs to fix update feed source introduce this problem.

UI: b47fd9
server: e7788f

**Comment by landonreed** [comment]
This was fixed by updating the server version on the dev server to 1c43be. The previously deployed server did not have the corresponding server PR. However, there still needs to be some additional work done to the server PR to make sure excessive data (e.g., feed version validation info) is not stored alongside the feed source document.
