### ISSUE TITLE
Error while doing mastarm build - related to main.js and woonerf module ?

### ISSUE THREAD

**Issue by wkulesza** [ibi-group/datatools-ui#657]
Hi,
when following the command:
```
mastarm build --config /path/to/configurations/dir
```
i'm getting this error, pointing to lack of main.js file.
Is that a know issue and could be fixed ?

```
root@test:/home/test/datatools-ui# mastarm build --config /home/test/datatools-ui/configurations/default
events.js:291
     throw er; // Unhandled 'error' event
     ^

Error: Can't walk dependency graph: Cannot find module '@conveyal/woonerf/mount' from '/home/test/datatools-ui/lib/main.js'
   required by /home/test/datatools-ui/lib/main.js
   at /usr/lib/node_modules/mastarm/node_modules/resolve/lib/async.js:137:35
   at processDirs (/usr/lib/node_modules/mastarm/node_modules/resolve/lib/async.js:290:39)
   at isdir (/usr/lib/node_modules/mastarm/node_modules/resolve/lib/async.js:297:32)
   at /usr/lib/node_modules/mastarm/node_modules/resolve/lib/async.js:25:69
   at FSReqCallback.oncomplete (fs.js:168:21)
Emitted 'error' event on Readable instance at:
   at Labeled.<anonymous> (/usr/lib/node_modules/mastarm/node_modules/read-only-stream/index.js:28:44)
   at Labeled.emit (events.js:314:20)
   at Labeled.<anonymous> (/usr/lib/node_modules/mastarm/node_modules/stream-splicer/index.js:130:18)
   at Labeled.emit (events.js:314:20)
   at Deps.<anonymous> (/usr/lib/node_modules/mastarm/node_modules/stream-splicer/index.js:130:18)
   at Deps.emit (events.js:314:20)
   at /usr/lib/node_modules/mastarm/node_modules/module-deps/index.js:387:25
   at onresolve (/usr/lib/node_modules/mastarm/node_modules/module-deps/index.js:185:25)
   at /usr/lib/node_modules/mastarm/node_modules/browserify/index.js:528:22
   at /usr/lib/node_modules/mastarm/node_modules/browser-resolve/index.js:265:24 {
code:  'MODULE_NOT_FOUND',
```

**Comment by landonreed** [comment]
Hi, I would recommend that you run `yarn build` rather than `mastarm build`. This should use the version of mastarm referenced from the `package.json` file and might fix the issue (but this is not something I've ever seen).

Also, just a reminder that we have an issue template for good reason: to help us quickly understand the context around the issue and come to a quicker resolution. Sharing info like the mastarm version, the branch/commit of datatools-ui you're using, and steps to reproduce is really the only way we can be helpful here.

**Comment by wkulesza** [comment]
@landonreed using the template, here's a fairly complete picture of database-ui running problem:

## Observed behavior
Build is successful, but when docker is started, it stops after some ~30secs with following error:
```
root@vps671012:/home/wojciech/datatools# docker logs 9fb2576993bd
npm notice
npm notice New minor version of npm available! 7.7.6 -> 7.10.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.10.0>
npm notice Run `npm install -g npm@7.10.0` to update!
npm notice
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
/opt/datatools-ui/node_modules/mastarm/lib/logger.js:26
  const strippedLinks = text.replace(/<[^|>]+\|([^>]+)>/g, '$1')
                             ^

TypeError: text.replace is not a function
    at emojify (/opt/datatools-ui/node_modules/mastarm/lib/logger.js:26:30)
    at Object.logToErrorConsole [as error] (/opt/datatools-ui/node_modules/mastarm/lib/logger.js:5:65)
    at /opt/datatools-ui/node_modules/mastarm/bin/mastarm-build:56:14
```

## Expected behavior

## Steps to reproduce the problem
Try using the Dockerfile (as i'm setting up 4 containers and trying to run all on my own dedicated server rather than s3 - datatools-mongodb, datatools-server, datatools-ui, datatools-nginx and datatools-postgres) below to build & start datatools-ui:
```
FROM node:latest
#TEST
ENV VERSION=dev
RUN apt-get update && \
    apt-get install -y --no-install-recommends gettext-base && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN npm i -g serve
RUN git clone -b dev https://github.com/ibi-group/datatools-ui.git /opt/datatools-ui
WORKDIR /opt/datatools-ui
# Add config directory
ADD ./config/*.yml /config/
RUN yarn
COPY /config/settings-client2.yml /opt/datatools-ui/configurations/default/settings.yml
EXPOSE 9966
CMD envsubst < /config/env-client.yml > /opt/datatools-ui/configurations/default/env.yml && \
    $(npm bin)/mastarm build --env production && serve -p 9966
```
Tried replacing mastarm build with yarn build but same error appeared.

settings-client2.yml that i'm copying to settings.yml is:
```
# Mastarm/deployment configuration properties. Note: application configuration
# is now taken entirely from server application (there are still some
# UI-specific env variables are in this repository's env.yml).
cloudfront: DEPLOY-DISTRIBUTION
entries:
  - 'lib/main.js:dist/index.js'
  - 'lib/index.css:dist/index.css'
s3Bucket: bucket-for-deployment
```

env-client.yml that i'm copying to env.yml is standard, but obviously with own auth0, mapbox tokens etc.

## Version of datatools-ui and datatools-server 
using the latest images and dev branches, so default ones

**Comment by wkulesza** [comment]
@landonreed you can close. I managed to overcome that problem by using node 12.13.0 instead of latest.

**Comment by landonreed** [comment]
Sounds good, and thanks for the update!
