### ISSUE TITLE
The following field(s) are missing from JSON feed_info object: [default_lang, feed_contact_email, feed_contact_url]

### ISSUE THREAD

**Issue by ovasens** [ibi-group/datatools-ui#782]
_**NOTE:** This issue system is intended for reporting bugs and tracking progress in software development. Although this software is licensed with an open-source license, any issue opened here may not be dealt with in a timely manner. [IBI Group](https://www.ibigroup.com/) is able to provide technical support for custom deployments of this software. Please contact [Ritesh Warade](mailto:ritesh.warade@ibigroup.com?subject=Data%20Tools%20inquiry%20via%20GitHub&body=Name:%20%0D%0AAgency/Company:%20%0D%0ABest%20date/time%20for%20a%20demo/discussion:%20%0D%0ADescription%20of%20needs:%20) if your company or organization is interested in opening a support contract with us. Please remove this note when creating the issue._

## Observed behavior (please include a screenshot if possible)
when trying to create a new feed info i got error below 
INFO  2022-04-12T03:39:44.536 [qtp1556438729-31] c.c.d.common.utils.SparkUtils(SparkUtils.java:243) res (500) contact@test.com POST: http://http://localhost:9966/api/editor/secure/feedinfo?feedId=270d4ba5-f6e2-407a-8ab1-07a42f9e89f5&sessionId=node0a9qsgy1edh5h10chjmhrf7ozq4
{
  "result" : "ERR",
  "message" : "An error was encountered while trying to save to the database",
  "code" : 500,
  "detail" : "The following field(s) are missing from JSON feed_info object: [default_lang, feed_contact_email, feed_contact_url]"
}
INFO  2022-04-12T03:39:44.536 [qtp1556438729-31] c.c.d.e.c.api.EditorController(EditorController.java:407) Create operation took 9 msec
INFO  2022-04-12T03:40:09.184 [qtp1556438729-42] c.c.d.common.utils.SparkUtils(SparkUtils.java:243) req contact@test.com POST: http://http://localhost:9966/api/editor/secure/feedinfo?feedId=270d4ba5-f6e2-407a-8ab1-07a42f9e89f5&sessionId=node0a9qsgy1edh5h10chjmhrf7ozq4
{
  "feed_id" : null,
  "feed_publisher_name" : "test",
  "feed_publisher_url" : "http://test.com",
  "feed_lang" : "fr",
  "feed_start_date" : null,
  "feed_end_date" : null,
  "default_route_color" : null,
...and 2 more lines
INFO  2022-04-12T03:40:09.186 [qtp1556438729-42] c.c.d.e.c.api.EditorController(EditorController.java:444) Updating session node0a9qsgy1edh5h10chjmhrf7ozq4 last edit time to 1649734809186
INFO  2022-04-12T03:40:09.187 [qtp1556438729-42] c.c.gtfs.loader.JdbcTableWriter(JdbcTableWriter.java:1404) select id from yafd_jvdykxjvitzilfkhumipct.feed_info where feed_publisher_name = 'test'
ERROR 2022-04-12T03:40:09.188 [qtp1556438729-42] c.c.gtfs.loader.JdbcTableWriter(JdbcTableWriter.java:245) Error creating feed_info entity
java.sql.SQLException: The following field(s) are missing from JSON feed_info object: [default_lang, feed_contact_email, feed_contact_url]
        at com.conveyal.gtfs.loader.JdbcTableWriter.setStatementParameters(JdbcTableWriter.java:477)
        at com.conveyal.gtfs.loader.JdbcTableWriter.createPreparedUpdate(JdbcTableWriter.java:375)
        at com.conveyal.gtfs.loader.JdbcTableWriter.update(JdbcTableWriter.java:150)
        at com.conveyal.gtfs.loader.JdbcTableWriter.create(JdbcTableWriter.java:115)
        at com.conveyal.datatools.editor.controllers.api.EditorController.createOrUpdate(EditorController.java:395)
        at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:530)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.base/java.lang.Thread.run(Thread.java:829)
java.sql.SQLException: The following field(s) are missing from JSON feed_info object: [default_lang, feed_contact_email, feed_contact_url]
        at com.conveyal.gtfs.loader.JdbcTableWriter.setStatementParameters(JdbcTableWriter.java:477)
        at com.conveyal.gtfs.loader.JdbcTableWriter.createPreparedUpdate(JdbcTableWriter.java:375)
        at com.conveyal.gtfs.loader.JdbcTableWriter.update(JdbcTableWriter.java:150)
        at com.conveyal.gtfs.loader.JdbcTableWriter.create(JdbcTableWriter.java:115)
        at com.conveyal.datatools.editor.controllers.api.EditorController.createOrUpdate(EditorController.java:395)
        at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:530)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.base/java.lang.Thread.run(Thread.java:829)
INFO  2022-04-12T03:40:09.190 [qtp1556438729-42] c.c.d.common.utils.SparkUtils(SparkUtils.java:136) Halting with status code 500.  Error message: An error was encountered while trying to save to the database

Please explain what is being observed within the application here.
create new feed info

Please explain what should happen instead.
fill the feed info form and click save icon

Please be as specific as possible.

## Any special notes on configuration used

Please describe any applicable config files that were used

## Version of datatools-ui and datatools-server if applicable (exact commit hash or branch name)

This info can be found by clicking on the gear icon on the sidebar

**Comment by ovasens** [comment]
I was trying a very old version ,
